version: '2.0'
services:
  rabbitmq:
    image: 'rabbitmq:3.8-management-alpine'
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      - '5672:5672'
      - '15672:15672'
  memcached:
    image: 'bitnami/memcached:latest'
    ports:
      - '11211:11211'